{"name": "test_mulFloat[0.2775-2-0.56]", "status": "failed", "statusDetails": {"message": "AssertionError: 实际结果0.555与预期结果0.56不一致\nassert 0.555 == 0.56", "trace": "self = <pytestSecond.test.testCalculator.TestCalculator object at 0x03B53280>, a = 0.2775, b = 2, expected = 0.56\n\n    @pytest.mark.run(order=3)\n    @pytest.mark.parametrize(['a', 'b', 'expected'], getData(\"mul\", \"floatDatas\"))\n    def test_mulFloat(self, a, b, expected):\n        result = self.cal.mul(a, b)\n>       assert result == expected, f'实际结果{result}与预期结果{expected}不一致'\nE       AssertionError: 实际结果0.555与预期结果0.56不一致\nE       assert 0.555 == 0.56\n\ntestCalculator.py:88: AssertionError"}, "parameters": [{"name": "a", "value": "0.2775"}, {"name": "b", "value": "2"}, {"name": "expected", "value": "0.56"}], "start": 1606204073442, "stop": 1606204073442, "uuid": "ba23e4a8-264b-4746-8b49-9ee7e7fa7d49", "historyId": "d1f67df0010d4dae6b2c74a84c516487", "testCaseId": "68b3df60cbff2423ec14039eaec5edd9", "fullName": "testCalculator.TestCalculator#test_mulFloat", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "testCalculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "DESKTOP-103B3LA"}, {"name": "thread", "value": "47728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCalculator"}]}